version: '3.8'

services:
  sse-server:
    build:
      context: .
      dockerfile: sse-Dockerfile
    container_name: mcp-sse-server
    environment:
      - NODE_ENV=production
      - VERCEL_API_KEY=${VERCEL_API_KEY}
    restart: unless-stopped