version: '3.8'

services:
  sse:
    build:
      context: .
      dockerfile: sse-Dockerfile
    command: pnpm run start-sse ${VERCEL_API_KEY}
    environment:
      - NODE_ENV=production
      - VERCEL_API_KEY=${VERCEL_API_KEY}
    labels:
      - "traefik.http.services.sse.loadbalancer.server.port=3001"
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped 