version: '3.8'

services:
  sse:
    build:
      context: .
      dockerfile: sse-Dockerfile
    command: pnpm run start-sse ${VERCEL_API_KEY}
    environment:
      - NODE_ENV=production
      - VERCEL_API_KEY=${VERCEL_API_KEY}
    labels:
      - "traefik.http.services.sse.loadbalancer.server.port=3001"
      - traefik.http.routers.sse.rule=Host(`mcp.domaingenius.com`)
      - traefik.http.routers.sse.entrypoints=https
      - traefik.http.routers.sse.service=sse
      - traefik.http.routers.sse.tls.certresolver=letsencrypt
      - traefik.http.routers.sse.tls=true

    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped 